# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Блок Важно знать', max_length=20, verbose_name='Название')),
                ('text', models.TextField(max_length=200, verbose_name='Блок Важно знать Текст')),
            ],
            options={
                'verbose_name': 'Блок Важно Знать Шапка Сайта',
            },
        ),
    ]
