# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_auto_20171031_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Название работы', max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Список Тип работ',
            },
        ),
    ]
