# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_typeofworks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Название услуги', max_length=20, verbose_name='Название')),
                ('description', models.CharField(default='Описание услуги', max_length=20, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name_plural': 'Список  Услуг',
                'verbose_name': 'Список  Услуг',
            },
        ),
        migrations.AlterModelOptions(
            name='interest',
            options={'verbose_name': 'Блок Важно Знать', 'verbose_name_plural': 'Блок Важно Знать'},
        ),
        migrations.AlterModelOptions(
            name='typeofworks',
            options={'verbose_name': 'Список Тип работ', 'verbose_name_plural': 'Список Тип работ'},
        ),
    ]
