# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_auto_20171101_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitems',
            name='description',
            field=models.CharField(default='Описание услуги', max_length=200, verbose_name='Описание'),
        ),
    ]
