# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0006_auto_20171101_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitems',
            name='price',
            field=models.CharField(default='0', max_length=20, verbose_name='Цена'),
        ),
    ]
