# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0007_auto_20171101_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('flag', models.BooleanField(default=False, verbose_name='Отобразить на сайте')),
            ],
            options={
                'verbose_name_plural': 'Отзывы клиентов',
                'verbose_name': 'Отзывы клиентов',
            },
        ),
    ]
