# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0008_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Как проехать')),
                ('path', models.TextField(verbose_name='Как добратся в сервис')),
                ('coords', models.URLField(verbose_name='Координаты google')),
            ],
            options={
                'verbose_name_plural': 'Координаты сервиса',
                'verbose_name': 'Координаты сервиса',
            },
        ),
    ]
