# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0009_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='steet',
            field=models.TextField(default='Юбилейный', verbose_name='Точный адрес'),
        ),
    ]
