# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0011_auto_20171102_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Описание услуги', max_length=200, verbose_name='Описание')),
                ('title', models.ForeignKey(default='Название услуги', on_delete=django.db.models.deletion.CASCADE, to='auto.TypeOfWorks', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Спектр  Услуг',
                'verbose_name_plural': 'Спектр  Услуг',
            },
        ),
        migrations.CreateModel(
            name='ServiceListTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Описание Тех регламента', max_length=200, verbose_name='Описание')),
                ('title', models.ForeignKey(default='Название услуги', on_delete=django.db.models.deletion.CASCADE, to='auto.TypeOfWorks', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тех  Регламент',
                'verbose_name_plural': 'Тех  Регламент',
            },
        ),
    ]
