# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0012_servicelist_servicelistto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOfWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40, verbose_name='Описание')),
                ('foto', models.ImageField(null=True, upload_to='works', verbose_name='Фото')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auto.TypeOfWorks', verbose_name='Название работы')),
            ],
            options={
                'verbose_name_plural': 'Описание работ и фото Главная страница + Галерея',
                'verbose_name': 'Описание работ и фото Главная страница + Галерея',
            },
        ),
        migrations.AlterModelOptions(
            name='serviceitems',
            options={'verbose_name': 'Список  Услуг и Цены', 'verbose_name_plural': 'Список  Услуг и Цены'},
        ),
    ]
